#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ViewerRatioLists.py

blacklist = [
    # Shooter games
    ['aim gods', '516967'], ['aim lab', '503456'],  ['anthem', '460696'],
    ['apex legends', '511224'], ['battlefield 1', '488500'], ['battlefield 2', '15467'], ['battlefield 2042', '514974'],
    ['battlefield 3', '24394'], ['battlefield 4', '66402'], ['battlefield v', '504199'],
    ['battlefield: bad company 2', '22851'], ['call of duty: black ops 4', '504462'],
    ['call of duty: black ops cold war', '512709'], ['call of duty: black ops ii', '34134'],
    ['call of duty: black ops iii', '489401'], ['call of duty: mobile', '512818'],
    ['call of duty: modern warfare', '1614555304'], ['call of duty: modern warfare 2', '22393'],
    ['call of duty: modern warfare remastered', '494155'], ['call of duty: vanguard', '492778073'],
    ['call of duty: warzone', '512710'], ['call of duty: wwii', '496712'], ['Vigor', '506489'],
    ['counter-strike: global offensive', '32399'], ['battlebit', '496916'], ['cruelty squad', '977894696'],
    ['destiny 2', '497057'], ['doom eternal', '506442'], ['escape from tarkov', '491931'], ['deathloop', '512983'],
    ['fallout 76', '506246'], ['f.e.a.r. perseus mandate', '14310'], ['gears 5', '506407'], ['Fallout 4', '489776'],
    ['grand theft auto iv: the ballad of gay tony', '2113221108'], ['grand theft auto v', '32982'], ['gtfo', '500627'],
    ['gunfire reborn', '517645'], ['gunz: the duel', '513567'], ['hitman', '491471'], ['hitman 3', '518011'],
    ['hell let loose', '497440'], ['hunt: showdown', '500188'], ['hyper scape', '518306'],
    ['insurgency: sandstorm', '491705'], ['max payne 3', '21222'], ['metal gear rising: revengeance', '24208'],
    ['metal gear solid', '14805'], ['metal gear solid 2: sons of liberty', '11386'], ['Metal Gear Acid', '8798'],
    ['metal gear solid 3: snake eater', '16582'], ['metal gear solid 4: guns of the patriots', '18893'],
    ['metro exodus', '497410'], ['mass effect legendary edition', '1568081763'], ['metroid prime 2: echoes', '1459'],
    ['payday 2', '65997'], ['outriders', '512930'], ['quake', '7348'], ['quake champions', '496253'],
    ['splitgate', '499310'], ['squad', '488479'], ['star wars battlefront ii', '492546'],
    ['returnal', '518019'], ['rogue company', '514194'], ['sniper elite 5', '511743'], ['team fortress 2', '16676'],
    ['the last of us', '33180'], ['the last of us part ii', '494552'], ["tom clancy's rainbow six siege", '460630'],
    ["tom clancy's rainbow six: siege", '460630'], ["tom clancy's the division", '369579'],
    ["tom clancy's the division 2", '504463'], ['titanfall 2', '489201'], ['Quake Live', '19490'],
    ['totally accurate battlegrounds', '506344'], ['true crime: new york city', '3077'], ['Adaca', '544704748'],
    ['Grand Theft Auto: San Andreas', '6521'], ['Uncharted 2: Among Thieves', '20357'], ['BIGFOOT', '6675'],
    ['Mass Effect 3', '26992'], ['S.T.A.L.K.E.R.: Anomaly', '1549167076'], ['Destiny', '280721'],
    ['DOOM II: Hell on Earth', '584'], ['Fallout: New Vegas', '23453'], ['Grand Theft Auto: Vice City', '15631'],
    ['Call of Duty: Black Ops', '23894'], ['Mafia II: Definitive Edition', '2058566581'], ['Gran Turismo 7', '518014'],
    ['Arma 3', '31750'], ['Far Cry 5', '497078'], ["Tom Clancy's Ghost Recon: Wildlands", '490379'], ['DOOM', '6715'],
    ['Grand Theft Auto III', '3412'], ['Crossfire', '27101'], ['Overwatch 2', '515025'],
    ['Family Battle: Tag Arena', '1871077473'], ['Zero Sievert', '324194362'], ['SCUM', '495811'],
    ['The Last of Us Remastered', '1200871695'], ['MechWarrior Online', '24623'], ['MetaOps', '1220570282'],
    ['Call of Duty 4: Modern Warfare', '1964'], ['APB Reloaded', '19157'], ['Krunker', '508391'],
    ['theHunter: Call of the Wild', '494683'], ['Evil Dead: The Game', '1022719138'], ['Mafia III', '490432'],
    ['Counter-Strike: Source', '10407'], ['Sudden Attack', '29068'], ['Borderlands', '18734'],
    ['Grand Theft Auto: San Andreas – The Definitive Edition', '89250567'], ['Holdfast: Nations At War', '498983'],
    ["Tom Clancy's Ghost Recon: Breakpoint", '512534'], ['MechWarrior 5: Mercenaries', '494684'],
    ['Grand Theft Auto: Vice City – The Definitive Edition', '957103328'], ['Ready or Not', '511701'],
    ['Call of Duty: Infinite Warfare', '491437'], ['Way of the Hunter', '489308483'], ['Prey', '15013'],
    ["Tom Clancy's Rainbow Six Extraction", '513004'], ['Deadpool', '509509'], ['Half-Life 2', '1420'],
    ["KovaaK's Aim Trainer", '510911'], ['Metal Gear Survive', '498026'], ['Counter-Strike', '10710'],
    ['Uncharted: The Lost Legacy', '494558'], ['World War Z: Aftermath', '1280358639'], ['Borderlands 2', '32345'],
    ['Days Gone', '497456'], ['ULTRAKILL', '514166'], ['Quake II', '2955'], ["Uncharted 4: A Thief's End", '458641'],
    ['Call of Duty 2', '2162'], ['Saints Row 2', '18906'], ['The Outer Worlds', '510580'], ['Star Valor', '508764'],
    ['Fashion Police Squad', '829294318'], ['Deep Rock Galactic', '494839'], ['Bioshock Infinite', '29099'],
    ['Enlisted', '505257'], ['Killing Floor 2', '460508'], ['BioShock Remastered', '2009742488'],
    # Bossfights
    ['bloodborne', '460636'], ['dark souls', '29433'], ['dark souls iii', '490292'], ['dark souls ii', '91423'],
    ['Elden Ring', '512953'], ["demon's souls", '21812'], ['hellpoint', '496421'], ['left 4 dead 2', '24193'],
    ['mortal shell', '516915'], ['nioh 2', '506468'], ['nioh 2: the complete edition', '160136078'],
    ['sekiro: shadows die twice', '506415'], ['the surge', '496233'], ['black mesa', '68016'],
    ['Company of Heroes 2', '65663'], ['Evolve Stage 2', '1893365738'], ['Metro: Last Light', '31836'],
    ['Dark Souls: Remastered', '1122982998'], ['Grand Theft Auto IV', '18707'], ['Fallout 3', '18763'],
    ['Nioh', '24872'], ['Kingdom Hearts III', '369585'],
    # Medieval fights
    ['chivalry 2', '512971'], ['for honor', '490382'], ['ghost of tsushima', '499856'], ['mordhau', '498859'],
    ['sifu', '506089309'], ['Warhammer: Vermintide 2', '498668'], ['Mortal Online 2', '517282'],
    ["Conqueror's Blade", '498523'],
    # Violent Survival
    ['dayz', '65632'], ['SurrounDead', '750209762'], ['Lost Light', '1706428735'],
    ['Dying Light 2: Stay Human', '506410'], ['Dying Light', '369380'], ['State of Decay 2', '495122'],
    # Fist fighting
    ['yakuza', '6571'], ['yakuza 0', '476269'], ['yakuza 5', '32541'], ['yakuza 6: the song of life', '490701'],
    ['yakuza: like a dragon', '512121'], ['lost judgment', '2120403770'], ['sleeping dogs', '26547'],
    ['Yakuza Kiwami 2', '498510'], ['Judgment', '509482'], ['Yakuza Kiwami', '490702'],
    # Drama
    ['among us', '510218'], ['Politics', '515214'], ['Gang Beasts', '459527'], ['Dread Hunger', '511181708'],
    ['The Walking Dead: The Telltale Series Collection', '499987'],
    # Horror
    ['back 4 blood', '511746'], ['resident evil 2', '8645'], ['resident evil 3: nemesis', '5126'],
    ['resident evil 7 biohazard', '492934'], ['resident evil village', '518017'], ['the evil within 2', '497437'],
    ['The Mortuary Assistant', '1945673289'], ['madison', '1535635666'], ['Video Horror Society', '642328546'],
    ['Resident Evil 5', '18808'], ['Silent Hill 2', '9891'], ['Resident Evil 6', '33437'], ['SOMA', '458224'],
    ['Melty Blood: Type Lumina', '936945829'], ['Dark Deception', '460018'], ['Resident Evil 3', '649775967'],
    ['Friday the 13th: The Game', '488518'], ['The Backrooms 1998', '624848592'], ['Visage', '494082'],
    ['Resident Evil: Deadly Silence', '352'], ['Poppy Playtime', '2058220722'], ['Forewarned', '783609948'],
    ['Resident Evil 4', '1468'], ['Resident Evil', '5360'], ['The Quarry', '1937599489'], ['Outlast', '73586'],
    ['The Dark Pictures Anthology: Man of Medan', '509249'], ["Five Nights at Freddy's", '418063'],
    ['Heavy Rain', '19423'], ['The Dark Pictures Anthology: House of Ashes', '1274531553'], ['Borderlands 3', '491318'],
    ['Vampire: The Masquerade - Bloodlines', '15062'], ['The Medium', '517401'], ['Amnesia: Rebirth', '516624'],
    ['Alien: Isolation', '458443'], ["Five Nights at Freddy's 4", '489567'], ['Stranger', '228183669'],
    ['Metal Gear Solid V: The Phantom Pain', '91419'], ['Friday the 13th', '19562'], ['Bullet Force', '502060'],
    ['Resident Evil 0', '489721'], ['Labyrinthine', '517528'], ['Ghost Watchers', '790163050'],
    ['Resident Evil 4: Otome Edition', '1638636362'], ['Phasmophobia', '518184'], ['The Beast Inside', '504389'],
    ['Refund Me If You Can', '866831809'], ["I'm on Observation Duty 5", '1654421360'], ['Deceit', '493244'],
    ['Ghost Exile', '289552769'], ['Silent Hill 3', '9522'], ['Resident Evil 4 HD', '784020615'],
    ['Is Simon There?', '443409039'], ['Silent Hill: Origins', '13206'], ['FOBIA: St. Dinfna Hotel', '2037799395'],
    ['Inside the Backrooms', '1144809661'], ['Amnesia: Rebirth', '516624'], ['Resident Evil Survivor', '14528'],
    ['The Evil Within', '68000'], ['The Evil Within 2', '497437'], ['Escape the Backrooms', '2066107586'],
    ['Resident Evil Resistance', '514308'], ['Song of Horror', '514930'], ['Darkwood', '313146'],
    ['Fear Therapy', '819777302'], ['Silent Hill', '3947'], ['Lunch Lady', '477532253'], ['Pacify', '511134'],
    ['Resident Evil: Revelations', '28576'], ['Standoff 2', '513501'], ['In Sound Mind', '518088'],
    ['Dead Space 2', '23017'], ['Dead Space', '19009'], ['Outlast II', '510117'],
    # Murder mystery
    ['gone home', '65752'], ["Handy Harry's Haunted House Services", '1450669133'],
    # Underwater
    ['Maneater', '506452'],
    # Story
    ['crysis', '10818'], ['death stranding', '494364'], ['far cry', '13564'], ['far cry 6', '518692'],
    ['halo infinite', '506416'], ['halo: reach', '24203'], ['halo: the master chief collection', '417969'],
    ['half-life', '2755'], ['red dead redemption 2', '493959'], ['halo 2', '6511'], ['Tomb Raider', '2770'],
    ['Far Cry: Primal', '490919'], ['Far Cry 3', '29635'], ['Rise of the Tomb Raider', '460620'],
    ['Tomb Raider II', '317'], ['Shadow of the Tomb Raider', '504735'],
    # Dungeon Crawler
    ['diablo ii', '1041'], ['diablo iii', '313558'], ['diablo iii: reaper of souls', '313558'],
    ['diablo immortal', '510150'], ['path of exile', '29307'], ['warframe', '66170'],
    ['Diablo II: Resurrected', '1788326126'], ['Devil May Cry 5', '506412'],
    # Dialogue game
    ['VA-11 HALL-A: Cyberpunk Bartender Action', '461529'],
    # Hide and seek
    ["garry's mod", '18846'], ['dead by daylight', '491487'], ['Monstrum 2', '519309'], ['Identity V', '508662'],
    ['Propnight', '1342987707'],
    # VR
    ['beat saber', '503116'], ['vrchat', '499003'], ['half-life: alyx', '515195'], ['DCS World', '313331'],
    ['Rec Room', '493280'], ['Pavlov VR', '496142'],
    # Stealth
    ['this land is my land', '512842'], ['Middle-earth: Shadow of Mordor', '458619'],
    # Money
    ['crypto', '499634'], ['horse racing', '6891'], ['poker quest', '308324368'], ['poker', '488190'],
    ['slots', '498566'], ['virtual casino', '29452'], ['Pokémon Trading Card Game Online', '32634'],
    ['Axie Infinity', '508967'], ['Stocks And Bonds', '5899'], ['Pokémon Trading Card Game', '9618'],
    ['Bitcoin', '515880'], ['Casino', '582382910'], ['Blackjack', '2030294088'], ['rFactor 2', '24636'],
    ['Lottery Simulator', '497156'],
    # Weird Sexual
    ['asmr', '509659'], ['pools, hot tubs, and beaches', '116747788'], ['Just Dance 2022', '413353439'],
    ['Hooked on You: A Dead by Daylight Dating Sim', '160028919'], ['Just Dance', '25122'],
    ['Beauty & Body Art', '509669'], ["Love, Money, Rock'n'Roll", '517967'],
    # Weird
    ["I'm Only Sleeping", '498592'], ['just chatting', '509658'], ['twitch plays', '491180'],
    ['watch parties', '515467'], ['Special Events', '509663'], ['Animals, Aquariums, and Zoos', '272263131'],
    ['Travel %26 Outdoors', '509672'], ['Games %2B Demos', '66082'], ['Talk Shows %26 Podcasts', '417752'],
    ['Sleep', '154096350'], ['Tarot', '83418'], ['Food%20%26%20Drink', '509667'], ['EZ2ON REBOOT : R', '2057185004'],
    ['Test, Test', '2070714813'], ['Lost in Play', '181659447'], ['The Simpsons: Hit %26 Run', '2897'],
    ['Pokémon Community Game', '329951934'],
    ['Bully', '9440'],
    # Weird DMCA
    ['Artifact', '16937'], ['El Chavo', '34054'], ['Movie Night', '753325070'], ['Music', '26936'],
    ['Anime World', '637756067'], ['Always On', '499973'], ['Sexy Miss', '1129360291'], ['The Simpsons', '2046821115'],
    ['Series Makers', '700055046'], ['Radio Station', '2128929587'], ['Karaoke Party', '488782'],
    ['Relaxing Waves', '872742502'], ['South Park', '8105'], ['Nothing', '1709696975'], ['TV Station Manager', '8259'],
    # Space
    ['elite: dangerous', '80607'], ['kerbal space program', '32742'], ['Starsector', '33416'],
    ['FTL: Faster Than Light', '33882'], ['Star Trek Fleet Command', '510530'], ['Star Citizen', '71375'],
    # Platformer and 2D fighting
    ['brawlhalla', '460316'], ['dragon ball fighterz', '497385'], ['guilty gear: strive', '517159'],
    ['m.u.g.e.n', '271231'], ['mortal kombat 11', '510578'], ['super smash bros. melee', '16282'],
    ['super smash bros. ultimate', '504461'], ['street fighter v', '488615'], ['tekken 7', '461067'],
    ['Legends of IdleOn', '1935520090'], ['Skullgirls: 2nd Encore', '764537219'], ['Touhou Project', '448375'],
    ['Granblue Fantasy: Versus', '510799'], ['Melty Blood: Type Lumina', '936945829'], ['MultiVersus', '950189725'],
    ['DRAGON BALL Z DOKKAN BATTLE', '489405'], ['SMASH LEGENDS', '519080'], ['DNF Duel', '108763890'],
    ['The King of Fighters XV', '513753'], ['Super Smash Bros. Brawl', '18833'], ['Dino Rex', '27887'],
    ['Super Smash Bros.', '17516'], ['Punch Planet', '494352'], ['Super Mario World', '1229'],
    ['Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles', '1414748474'], ['Skullgirls', '30639'],
    ['Ultimate Marvel vs. Capcom 3', '1336067913'], ['Guilty Gear XX Accent Core Plus R', '491467'],
    ['Ultra Street Fighter IV', '313164'], ['Ultimate Mortal Kombat 3', '1999'], ['SoulCalibur VI', '500626'],
    ['MapleStory', '19976'], ["The King of Fighters '98", '9747'],
    # Sports
    ['cricket 19', '512623'], ['ea sports ufc 4', '518711'], ['efootball pes 2021 season update', '1520501777'],
    ['fifa 16', '489608'], ['fifa 17', '493091'], ['fifa 18', '495589'], ['fifa 19', '506103'], ['fifa 20', '512804'],
    ['fifa 21', '518204'], ['fifa 22', '1869092879'], ['football manager 2021', '1271244884'],
    ['football manager 2022', '586622463'], ['madden nfl 21', '517406'], ['madden nfl 22', '966064811'],
    ['wwe 2k19', '508289'], ['wwe 2k20', '513681'], ['wwe 2k22', '1199725270'], ['nba 2k21', '518023'],
    ['nba 2k22', '1371363232'], ['nhl 21', '519329'], ['mlb the show 21', '1160459167'], ['pga tour 2k21', '517397'],
    ['slam dunk', '517301'], ['sports', '518203'], ["Tiny Tina's Wonderlands", '1318043161'], ['NHL 22', '13932618'],
    ['Blood Bowl 2', '490177'], ['Out of the Park Baseball 23', '123403711'], ['WWE SuperCard', '461427'],
    ['Fitness%20%26%20Health', '509671'], ['eFootball 2022', '1061323687'], ['MLB The Show 22', '1820819463'],
    ['Russian Fishing 4', '497304'], ['fifa 23', '1745202732'], ['MLB 9 Innings 22', '2038575831'],
    ['WWE Champions', '491560'], ['Fishing Planet', '491117'], ['Italia 1990', '14824'], ['Assetto Corsa', '313197'],
    ['Captain Tsubasa II: Super Striker', '579601296'], ['FIFA Online 4', '504798'], ['Anstoss 3', '498350675'],
    ['Pro Soccer Online', '1286420756'], ['NCAA Football 14', '271198'], ['Madden NFL 23', '862021340'],
    ['mario strikers: battle league', '1769394593'],
    # Vehicles
    ['Microsoft Flight Simulator', '7193'],
    # Racing
    ['f1 2020', '517174'], ['f1 2021', '752590871'], ['iracing', '19554'], ['Assetto Corsa Competizione', '1348809580'],
    ['F1 22', '1705795372'], ['CarX Drift Racing Online', '498289'], ['Need for Speed: Underground', '11258'],
    ['Forza Horizon 5', '1757732267'], ['Stuntfest Worldtour', '1582771097'], ['The Crew 2', '497118'],
    ['NASCAR Heat 5', '517409'], ['Need for Speed Heat', '512782'], ['Need for Speed: Underground 2', '8855'],
    ['BeamNG.drive', '491878'], ['Mario Kart 8 Deluxe', '941530474'],
    # Speedrun
    ['Hot Lava', '498346'], ['Spyro the Dragon', '7182'], ['Super Mario 64', '2692'], ['Super Metroid', '7595'],
    ['Metroid Prime', '14198'], ['Sonic the Hedgehog', '2271'], ['The Legend of Zelda: A Link to the Past', '9435'],
    ['Spyro the Dragon: Reignited Trilogy', '1885901697'], ["The Legend of Zelda: Majora's Mask", '12482'],
    ['Sonic Origins', '914065119'], ['Castlevania: Symphony of the Night', '13050'], ['Super Mario Maker 2', '511399'],
    ['Ratchet %26 Clank', '16791'],
    # Battle Royale
    ['fortnite', '33214'], ['fall guys', '512980'], ['Garena Free Fire', '502732'], ['Naraka: Bladepoint', '515474'],
    ['pubg: battlegrounds', '493057'], ["playerunknown's battlegrounds", '493057'], ['Super Animal Royale', '509529'],
    ['super people', '19620578'], ['warzone', '25416'], ['Stumble Guys', '1312214340'], ['Crab Game', '673760473'],
    ['Realm Royale', '505845'], ['Rush Royale', '633454324'], ['Rumbleverse', '161880494'],
    ['Z1: Battle Royale', '417892'],
    # Old
    ['Ape Escape', '12270'],  ['Retro', '27284'],
    # War
    ['war thunder', '66366'], ['world of tanks', '27546'], ['world of warships', '32502'], ['Foxhole', '493388'],
    ['World of Tanks Console', '499551'], ['World of tanks: Blitz', '140035'], ['crossout', '492113'],
    ['Steel Division 2', '511940'], ['World of Warships: Legends', '512226'],
    # Minigames with or without chat
    ['Kukoro: Stream Chat Games', '518764'], ['Words On Stream', '512821'], ['Jackbox Party Packs', '493174'],
    ['Kahoot!', '1127100998'], ['Wordle', '879648744'], ['What The Dub?!', '752874500'],
    ['The Jackbox Party Pack 9', '1219652274'],
    # Anime fighter
    ['Dragon Ball Z: Kakarot', '511195'], ['Naruto to Boruto: Shinobi Striker', '496503'],
    # Competitive
    ['dota 2', '29595'], ['smite', '32507'], ['overwatch', '488552'], ['Smite', '32507'], ['starcraft ii', '490422'],
    ['StarCraft', '11989'], ['Warcraft III', '12924'], ['valorant', '516575'], ['Age of Empires II', '13389'],
    ['Total War: Warhammer III', '1913410799'], ['EVE Online', '13263'],
    ['Age of Empires III', '7830'], ['Age of Empires IV', '498482'], ['Total War: Warhammer II', '497434'],
    ['Warhammer Online: Age of Reckoning', '18888'], ['World of Warcraft', '18122'],
    # Competitive non violent
    ['Splatoon 2', '495064'], ['Knockout City', '1924769596'],
    # Competitive deck builders
    ['Gwent: The Witcher Card Game', '493217'], ['Hearthstone', '138585'], ['Magic: The Gathering', '2748'],
    ['Yu-Gi-Oh! TRADING CARD GAME', '497248'], ['Yu-Gi-Oh! Duel Links', '494508'], ['Storybook Brawl', '1210837377'],
    ['Yu-Gi-Oh! Forbidden Memories', '207'], ['Yu-Gi-Oh! Master Duel', '1119642287'],
    # Competitive weird
    ['Bloons TD Battles 2', '1740011318'], ['Chess', '743'], ['Go', '65360'], ['Mahjong Soul', '512708'],
    # Turn based combat
    ['Heroes of Might and Magic III: The Restoration of Erathia', '12839'], ['XCOM 2', '489767'],
    ["Sid Meier's Civilization VI", '492553'], ['XCOM: Enemy Unknown', '33331'], ['Hearts of Iron IV', '459327'],
    ['Europa Universalis IV', '67584'], ['Slay the Spire', '496902'], ['Final Fantasy VII', '11988'],
    ['Chrono Trigger', '8489'], ['Crusader Kings III', '514888'], ['Kingdom Hearts HD 1.5 %2B 2.5 ReMIX', '494099'],
    ['Age of Mythology', '1260'], ['Age of Mythology: Extended Edition', '421115841'],
    ['Xenoblade Chronicles: Definitive Edition', '514245'], ['Darkest Dungeon', '458353'],
    # Games for 2
    ['We Were Here Forever', '428452832'], ['Codenames', '508509'], ['Keep Talking and Nobody Explodes', '461492'],
    ['Gartic Phone', '278888515'], ['It Takes Two', '518213'], ['Tabletop RPGs', '509664'], ['Pummel Party', '509549'],
    ['A Way Out', '497388'],
    # Games for groups
    ['Dungeons%20%26%20Dragons', '509577'], ['Music Quiz', '24786'], ['Mafia LIVE!', '22761'],
    ['Monopoly Plus', '493159'], ['Masks Of Deception', '519297364'], ['PlateUp!', '1115711128'],
    ['Overcooked! 2', '506458'], ['UNO', '11103'],
    # Mobile
    ['langrisser mobile', '509986'], ['league of legends: wild rift', '514858'], ['Dragon Ball Legends', '504921'],
    ['Mobile Legends: Bang Bang', '494184'], ['MARVEL Strike Force', '504651'], ['Epic Seven', '510056'],
    ['Fate%2FGrand Order', '493048'], ['One Piece: Treasure Cruise', '489169'], ['Marvel Snap', '1743359147'],
    ['MARVEL Contest of Champions', '461221'], ['Last Day on Earth: Survival', '497697'],
    ['Apex Legends Mobile', '170987874'], ['Saint Seiya: Awakening', '511850'], ['Brawl stars', '497497'],
    ['Final Fantasy Tactics', '18181'], ['Dungeon %26 Fighter Mobile', '1013109068'], ['Bleach: Brave Souls', '492984'],
    ['Dead by Daylight Mobile', '517072'], ['pubg mobile', '505884'], ['FIFA Mobile', '496320'],
    ['Summoners War: Sky Arena', '489111'], ['Clash Royale', '491168'], ['Clash of Clans', '73914'],
    # Playstation 4
    ['Dreams', '490373'],
    # Nintendo Switch
    ['The Legend of Zelda: Skyward Sword HD', '1829367372'], ['Pokémon Legends: Arceus', '561013832'],
    ['Super Mario Odyssey', '493997'], ["Luigi's Mansion 3", '509541'], ['Pokémon Sword%2FShield', '497451'],
    ['Pokémon Brilliant Diamond%2FShining Pearl', '1584745140'],
    # Nintendo WII
    ['Mario Kart Wii', '18871']
]

newBlacklistAdditions = []

favoriteGames = [
    # Games I enjoy the most at the moment
    'Satisfactory',
    # Survival
    'Minecraft', 'Terraria', 'Vintage Story', 'Valheim', 'Icarus', 'Raft', 'Atlas', 'Ark', 'Creativerse',
    'Ark: Survival Evolved',
    # City bulding
    'Cities: Skylines', 'SimCity',
    # Villagers
    'Stardew Valley', 'Dinkum', 'Animal Crossing: New Horizons',
    # Automation
    'Factorio', 'Hydroneer', 'Captain of industry', 'Rimworld', 'Dorfromantik', 'Snowrunner', 'Mini Motorways',
    # Simulation
    'The Sims 4', 'The Sims 3', 'The Sims 2', 'The Universim', 'Oxygen Not Included',
    # Strategy
    'Going medieval', 'Mount & Blade: Warband', 'Mount & Blade II: Bannerlord',
    'Teamfight Tactics', 'Auto Chess'
    # Weird
    'Reading Fun', 'Roblox', 'Duolingo', 'Viscera Cleanup Detail', 'Tetris 99',
    # Board games
    'Chess', 'Tabletop Simulator', 'Card Games', 'Board Games',
    # Racing
    'Trackmania', 'Rocket League',
    # Special
    'Art', 'Makers & Crafting', 'Software and Game Development', 'Science & Technology',
    # Sports
    'Golf With Your Friends', "Tony Hawk's Pro Skater 1+2",
    # Story
    "Assassin's Creed Odyssey", "Assassin's Creed Origins", "Assassin's Creed IV Black Flag",
    "Assassin's Creed Valhalla", "Assassin's Creed Unity", "Assassin's Creed II",
    # Platformer
    'Super Meat Boy',
    # Hate but love
    'League of Legends', 'Heroes of the Storm',
    # RPG
    'Gothic', 'Gothic II', 'Lost Ark', 'Old School RuneScape', 'TERA',
    # Mobile
    'Pokémon GO'
]

streamersAbove1000Avg = [
    "summit1g",
    "lifeisbeautiful",
    "Pinnacle",
    "Crown",
    "NRG_Hamlinz",
    "PocketGamerLive",
    "Clix",
    "bhvrinteractive",
    "Jerma985",
    "Stacey_Xorris",
    "OldSpice",
    "RiotGames2",
    "Xposedyq",
    "Halo",
    "Mary_Eown",
    "xpandaAQ",
    "sapnaplive",
    "buddha",
    "Halsey",
    "galaxyracerdxb1",
    "Xposedtd",
    "aceu",
    "Xposednl",
    "zenniieeee",
    "RatedEpicz",
    "Philza",
    "4freakshow",
    "Ramee",
    "Unboxholics",
    "LPL",
    "hyckfullsun",
    "LiveNation",
    "DoorDash",
    "minsungislove",
    "JBL_Audio",
    "jaemlerenj",
    "Kyedae",
    "thereislight",
    "yaethereup",
    "Stacey_Porris",
    "Mary_Rown",
    "Olivia_Yallis",
    "yourragegaming",
    "Fortnite",
    "Markiplier",
    "TubboLIVE",
    "ILANDU2",
    "Rekkles",
    "Ninja",
    "PaymoneyWubby",
    "jacksepticeye",
    "Zerkaa",
    "Mary_Wown",
    "StateFarm",
    "Mary_Gown",
    "MOONMOON",
    "MiraculousTO",
    "k3soju",
    "Lucy_Ailson",
    "Vitalikqk_Crypto",
    "CapcomUSA",
    "Vitaliknt_Crypto",
    "SIAwards",
    "Bjergsenlol",
    "EASPORTSFIFA",
    "Thebausffs",
    "tastemade",
    "Iecca_Rich",
    "VShojo",
    "TwitchRivals",
    "Gorgc",
    "Chipotle",
    "Mary_Oown",
    "moistcr1tikal",
    "safemoonprotocol",
    "PGL_DOTA2EN2",
    "evo2",
    "PlayOverwatch",
    "BattlestateGames",
    "AmazonMusic",
    "Opera_GX",
    "PGL_DOTA2EN4",
    "LVNDMARK",
    "iiTzTimmy",
    "Lucy_Pilson",
    "jeongyunonly",
    "VitalikkCrypto",
    "Emiru",
    "evo5",
    "Olivia_Dallis",
    "GamesDoneQuick",
    "Xposedqj",
    "ESL_CSGO",
    "finalfantasyxiv",
    "EAMaddenNFL",
    "postmaloneissocool",
    "Mary_Zown",
    "ze34_zinnia",
    "VitalikcoCrypto",
    "RocketLeagueAPAC",
    "",
    "Grimm",
    "sanshinestreams",
    "Aztecross",
    "valorantesports2",
    "Psychoghost",
    "nihmune",
    "VitalikshETH",
    "THERUSSIANBADGER",
    "KEOXER",
    "Taylor_Jevaux",
    "Tanya_Henton",
    "VitalikeqCrypto",
    "VitalikukCrypto",
    "kstreamZQ",
    "ClassyBeef",
    "taxi2g",
    "Vitalikza_Invests",
    "TheChief1114",
    "punzlmao",
    "Vitalik_EventsTN",
    "Vitalikea_Crypto",
    "Luna_Eitters",
    "DanTDM",
    "WikiVellow",
    "AquaFPS",
    "1leaff",
    "Natsumiii",
    "Zayt",
    "ChrisMoylesShow",
    "UpOnlyTV",
    "Shotzzy",
    "lokalantreasure",
    "DatModz",
    "VitalikButerinje",
    "Larldotadog",
    "Scripe",
    "CNEGames",
    "Vitalik_EventsBX",
    "Wolfabelle",
    "aDrive",
    "Dropped",
    "CTRL_Music_",
    "BoomerNA",
    "ESL_CSGO_GG",
    "RollingStone",
    "Tanya_Wenton",
    "ploroorplo",
    "AFROPUNK",
    "smallmanbigworld",
    "FENGRUSH",
    "sips_",
    "niki_eliiemoa",
    "jamesmarriott",
    "VitalikanETH",
    "dafran",
    "Priscilla_Senton",
    "Serral",
    "RuneScape",
    "BorasLegend",
    "iWOOSUNG",
    "kurtisconner",
    "Ayrun",
    "eltiovitox",
    "Vitalikvi_Crypto",
    "Gillette",
    "Konvy",
    "TobiasFate",
    "bateson87",
    "mL7support",
    "AlcastHQ",
    "Rose_Qatts",
    "NymN",
    "iBestieSwift",
    "Xposedqa",
    "vaxei_osu",
    "Dayna_Xawns",
    "saltedsalmoooon",
    "omocat",
    "s00bining",
    "WillerZ",
    "GDC",
    "starsmitten",
    "Xposedvp",
    "btssmash3",
    "VitalikoaCrypto",
    "Ray",
    "Vitalikvj_Crypto",
    "monbewenee7",
    "Payo",
    "whitecatosu",
    "SweeetTails",
    "DannyGoonzalez",
    "btssmash2",
    "VitalikhmCrypto",
    "BeyondTheSummit2",
    "VitalikiyCrypto",
    "Sweet_Anita",
    "Emma_Sones",
    "PikameeAmano",
    "Vitalikpp_Crypto",
    "Vitalikrq_Crypto",
    "OkCode",
    "Vitalikkg_Crypto",
    "Ssaab",
    "TritonPoker",
    "VitalikpuCrypto",
    "Stacey_Griggs",
    "BTMC",
    "ardbeg_uk",
    "MogTalk",
    "ZubatLEL",
    "Hungrybox",
    "susu_jpg",
    "Grizzy",
    "SunBaconRelaxer",
    "blncgjk",
    "Faux",
    "StarLadder_cs_en",
    "Luna_Uitters",
    "jeongpremium",
    "VitalikisETH",
    "Vitalikll_Invests",
    "baoo",
    "Formula1",
    "VitalikccCrypto",
    "Grubby",
    "Mia_Jcotts",
    "VitalikafCrypto",
    "ESL_Dota2d",
    "OhTofu",
    "Dayna_Mawns",
    "Vitalikve_Crypto",
    "VitalikTZButerin",
    "xChocoBars",
    "Lysium",
    "VitalikmmETH",
    "GonzaRive98",
    "EASPORTSFIFAMobile",
    "VitalikwfCrypto",
    "officiallyOUTLOUD",
    "G2Esports",
    "Calebhart42",
    "Nemz38",
    "SwaggerSouls",
    "neimki",
    "Kate_Lawns",
    "AxieInfinityce",
    "iateyourpie",
    "TroydanGaming",
    "TangoTek",
    "Tobii",
    "Giantwaffle",
    "moveforwardmusic",
    "VitaliktdCrypto",
    "crylixblooom",
    "St1mpee",
    "VitalikWUButerin",
    "Daisy_Aatts",
    "Scrapie",
    "KabajiOW",
    "VitalikhhCrypto",
    "I_LAND_U2",
    "Macey_Xawns",
    "vpsportstalker",
    "sleepy",
    "xxtickteukxx",
    "Becca",
    "AriaSaki",
    "Macey_Eawns",
    "stormen",
    "Vitalik_ETH17",
    "Vitalikcd_Crypto",
    "Lacari",
    "brokenblade",
    "ESL_CSGOc",
    "FarhadXRay",
    "harbleu",
    "torranx",
    "WildRiftEsports",
    "Luna_Aitters",
    "xhocii",
    "valorantesports3",
    "VitalikzkCrypto",
    "TheRSGuywcf",
    "antonychenn",
    "btsnewsbrasil",
    "Chloe_Sasing",
    "VitaliktnCrypto",
    "Vitalik_EventsVD",
    "Rug",
    "Stacey_Kriggs",
    "VitalikgqCrypto",
    "jadeslittlehun",
    "TheAn1meMan",
    "SmashFactorGaming",
    "syn4ack",
    "Sydeon",
    "Jodie_Pryan",
    "ugelperu",
    "puppyjamz",
    "TGLTN",
    "proyectoinokbiss",
    "ladygagaagogo",
    "TwitchCalgary",
    "zwebackhd",
    "Daisy_Nilliams",
    "CoreJJ",
    "docm77LIVE",
    "Vitalikbd_Foundation",
    "Zoil",
    "Vitalikib_Crypto",
    "Vitalik_ETH59",
    "andersonjph",
    "Tanya_Venton",
    "Mia_Qcotts",
    "PimpCSGO",
    "Kate_Xawns",
    "Luna_Fitters",
    "ethfoundcrypto",
    "VitalikhnCrypto",
    "itsHafu",
    "LegendsofRuneterra",
    "VitalikwtCrypto",
    "Luna_Sitters",
    "DropsByPonk",
    "Techland",
    "VitalikhlETH",
    "VitalikmeCrypto",
    "TheSims",
    "Daisy_Silliams",
    "Strippin",
    "iloveboys69420",
    "VitalikbwETH",
    "Vitalikow_Crypto",
    "iskall85",
    "JuniperActias",
    "VitalikcdCrypto",
    "Ohmwrecker",
    "Tyceno",
    "hootyhooots",
    "sono_ariete",
    "Luna_Iitters",
    "crokeyz",
    "BobRoss",
    "ZeplaHQ",
    "keanelol",
    "ohnePixel",
    "Stacey_Jriggs",
    "f1ultrarealisticmod",
    "Vitalik_EventsYV",
    "atlus_west",
    "ash",
    "coinbilly_",
    "Deansocool",
    "aliensrock",
    "Loeya",
    "Betty_Patilda",
    "VitalikzrCrypto",
    "RasslinStreamsHD",
    "Naowh",
    "SmoshGames",
    "Erika_Pones",
    "alpharad",
    "arsenalpresser",
    "Vitalik_EventsZK",
    "VitalikwyCrypto",
    "g4tvesports",
    "Day9tv",
    "jenoisprince",
    "BDLG",
    "Aurateur",
    "diceyzx",
    "Nikolarn",
    "Mikaylah",
    "Cheesur",
    "TeamfightTactics",
    "VitalikfvCrypto",
    "WooxSolohah",
    "beautie_",
    "fl0m",
    "Vitalikll_ETH",
    "Vitalikqc_Buterin",
    "Pokemon",
    "CastleSuperBeast",
    "VitalikxlCrypto",
    "VitalikoiCrypto",
    "kingpyntv",
    "Criken",
    "sirkim96",
    "Macey_Lawns",
    "rolfzkie",
    "VitalikknCrypto",
    "VitalikqeCrypto",
    "neeko",
    "TrixieMattel",
    "VitalikgrCrypto",
    "WorldTitleMatchDraughts",
    "Rizzo",
    "Vitalikdi_Crypto",
    "aleks",
    "VitalikepETH",
    "SpookyLoopz",
    "Farfa",
    "MapleStory",
    "Chloe_Jasing",
    "HutchMF",
    "Evasion_GG",
    "HisWattson",
    "Vitalik_ETH63",
    "boggy110",
    "Vitalik_EventsOE",
    "VitalikhqCrypto",
    "Artosis",
    "dhtekkz",
    "AsianGuyStream",
    "Dayna_Uawns",
    "Vienna",
    "Welyn",
    "maryisidro",
    "itsJadeyAnh",
    "Jessu",
    "Vitalikiq_Crypto",
    "Bawkbasoup",
    "Hajime",
    "nhk_g",
    "snowlive1",
    "VitalikbdCrypto",
    "neyasosnogorez",
    "MARVELSNAP",
    "VitalikclCrypto",
    "SWTOR",
    "PokemonGO",
    "Vitalikjv_Invests",
    "VitalikyvCrypto",
    "robinsongz",
    "cuptoast",
    "VitalikyuCrypto",
    "Umbra",
    "ibabyrainbow",
    "BladeandSoul",
    "TheDooo_",
    "AxieInfinitykm",
    "Tayy",
    "Mia_Dcotts",
    "aseulrene_23",
    "Priscilla_Wenton",
    "1000dreamsfund",
    "Priscilla_Fenton",
    "Luna_Jitters",
    "Stacey_Sriggs",
    "Vitalikcf_Crypto",
    "Misstrixtin",
    "Priscilla_Nenton",
    "BurkeBlack",
    "Sweatcicle",
    "Ben_",
    "arsenalofficial",
    "supcaitlin",
    "Hera",
    "Noko",
    "fifakillvizualz",
    "emimartinez92",
    "Vitalik_ETH51",
    "Behzinga",
    "VitaliklpCrypto",
    "miamalkova",
    "Luna_Ditters",
    "WooxSoloixe",
    "HAchubby",
    "Central_Committee",
    "Vitalik_ETH32",
    "ONSCREEN",
    "Albralelie",
    "jakenbakeLIVE",
    "Skermz",
    "Dashy",
    "Vitalikvr_ETH",
    "examani",
    "DBook",
    "Vitalik_EventsNV",
    "GCXEvent",
    "Amaz",
    "btssmash",
    "TaliaMar",
    "VitalikeoETH",
    "Vitaliklb_Crypto",
    "Rescue",
    "livinginhopeworld",
    "simpson_mania05",
    "IKeepItTaco",
    "Tanya_Tenton",
    "LatinxInGames",
    "idubbbz",
    "nlechoppamusic1",
    "sunflowerjuyeon",
    "SnaggyMo",
    "NBA",
    "Flights1",
    "VitalikhCrypto",
    "AverageJonas",
    "Ranger",
    "m0xyy",
    "CAMOMO_10",
    "OfficialBoaster",
    "NoiceGuy",
    "LegionFarm_Official",
    "Kate_Mmith",
    "koresh13cm",
    "VitalikfoCrypto",
    "Anomaly",
    "MotionlessInWhite",
    "Timmac",
    "Crypto_Newss",
    "Vitalikai_Foundation",
    "BrookeAB",
    "PegaxyOfficial",
    "festivalceremonia",
    "tenspencils",
    "CookSux",
    "Bronx",
    "AxieInfinitybo",
    "VitalikzcCrypto",
    "Vitalikfc_Crypto",
    "Rose_Satts",
    "ksilittlebrothermatch2",
    "GeneralSniper",
    "seomaria",
    "Crytek",
    "FEDMYSTER",
    "GabSmolders",
    "VitalikrcCrypto",
    "BEMBARA",
    "Ac7ionMan",
    "whereswossy",
    "Bwipolol",
    "anny",
    "ProBrawlhalla",
    "VitalikrgCrypto",
    "PokemonChallenges",
    "dish",
    "swimstrim",
    "Tanya_Penton",
    "RichardLewisReports",
    "nostale_official",
    "VitalikppCrypto",
    "RaiseYourEdge",
    "yvonnie",
    "P2istheName",
    "LDNUTD",
    "ripple_xrp1",
    "Sanchovies",
    "SheepFarmer",
    "MurderCrumpet",
    "XenosysVex",
    "Dayna_Rawns",
    "VitaliksjCrypto",
    "VitaliksyCrypto",
    "yejuniverse",
    "Tilly_Iawns",
    "Forky",
    "Vitalik_ETH18",
    "KaijukeyMonz",
    "AxieInfinityqk",
    "Tanya_Centon",
    "VitalikitCrypto",
    "Vitalikmf_ETH",
    "Macey_Rawns",
    "Savjz",
    "Seukichu",
    "Zaelia",
    "yunopremium",
    "VitalikMQButerin",
    "AxieInfinityhy",
    "jakepaul_vs_woodley2_nd",
    "druski",
    "Kalei",
    "VitalikvtCrypto",
    "BEATesports",
    "TapL",
    "ImNio",
    "Daisy_Filliams",
    "VitaliketCrypto",
    "ANGRYPUG",
    "dreamies_0813",
    "TwitchLondon",
    "Marzzzzy",
    "Macey_Uawns",
    "veroniquezc",
    "Vitalikkk_Crypto",
    "xum8nghao_o2",
    "TwistzzTV",
    "asianbunnyx",
    "CashNastyGaming",
    "WooxSoloukk",
    "Smajor",
    "loustreams",
    "PlayKakaoGames",
    "Becca_Hichmond",
    "RaidiantGG",
    "Rebecca_Bmber",
    "Daisy_Ratts",
    "AxieInfinityhn",
    "VitalikzlCrypto",
    "VitalikepCrypto",
    "Dzukill",
    "VitalikmxCrypto",
    "DrewCurtis",
    "Stacey_Nriggs",
    "LoLWorldChampionship",
    "bananabrea",
    "Betty_Zatilda",
    "Granny",
    "FunkyP",
    "Daisy_Qatts",
    "brax",
    "Chloe_Oasing",
    "viva_con_agua",
    "Daisy_Catts",
    "VitaliktwCrypto",
    "JimmyHere",
    "NHL",
    "GMNaroditsky",
    "VitalikabCrypto",
    "RaizQT",
    "Alliance",
    "keshi",
    "VitalikymCrypto",
    "dronechampionsleague",
    "Vitalik_ETH90",
    "iGumdrop",
    "St0rm__x",
    "MOTOR",
    "IllustratedWorldSeries",
    "trinki_asmr",
    "tonkaaaaP",
    "Bandsintown",
    "hyyh_log",
    "Complexity",
    "ShubbleYT",
    "Spraggy",
    "Quantum",
    "chocoTaco",
    "Vitalikuf_Foundation",
    "Prettyboyfredo",
    "gamergirl",
    "lagrupalive",
    "thecaptaindavo",
    "Vitalikma_Crypto",
    "Betty_Watilda",
    "Stacey_Criggs",
    "WooxSolofzx",
    "Vitalik_ETH1",
    "Vitalikse_ETH",
    "reneesrealm",
    "Hafthorjulius",
    "lollapaloozaarg2",
    "zombs",
    "Vitalikuu_Crypto",
    "Vitalikuo_ETH",
    "JoltzDude139",
    "DanucD",
    "meyiieeehhhh",
    "Macey_Hawns",
    "mely_z3ld4",
    "Emongg",
    "WooxSoloorx",
    "Tanya_Jenton",
    "StaysafeTV",
    "AtomicMari",
    "Tanya_Renton",
    "LaurenAlexis_x",
    "n3on",
    "Macey_Tawns",
    "fobm4ster",
    "deyyszn",
    "Tanya_Rcotts",
    "TheMrSark",
    "PrimeGaming",
    "Lolathon",
    "ArcticGE",
    "filian",
    "WooxSolodij",
    "WendyBellRadio",
    "uflgame",
    "betway_b",
    "Funcom",
    "Kate_Tawns",
    "Dayna_Nawns",
    "Stacey_Vriggs",
    "VitaliklwCrypto",
    "Vitalikgu_Foundation",
    "illumina1337",
    "VitalikWNButerin",
    "Kate_Vmith",
    "GarrettG",
    "nothaddzy",
    "EpicSeven",
    "Xlice",
    "jccaylen",
    "Florryworry",
    "Sco",
    "OverwatchContenders",
    "agrandeao",
    "Paige_Higgs",
    "KarasMai",
    "Terroriser",
    "AshesofCreation",
    "Vitaliksj_Buterin",
    "Intel",
    "Dayna_Aawns",
    "buzzingfortune",
    "ahddub_",
    "NomNom",
    "VitalikwjCrypto",
    "VitalikqrCrypto",
    "ZombiUnicorn",
    "pkhdx",
    "qwerty_adgjl",
    "clashofthestarstv",
    "sunsetgaiaASMR",
    "vitoxwwe",
    "imdavisssv2",
    "DarkflameUniverse",
    "19304s",
    "KOT4Q",
    "Dayna_Tawns",
    "Tanya_Zenton",
    "Captainflowers22",
    "Lucy_Cilliams",
    "Daisy_Xilliams",
    "Paige_Siggs",
    "5up",
    "VitalikjcCrypto",
    "mamamobuang",
    "MacieJay",
    "Emma_Cones",
    "MitchManCasting",
    "eltiovitoxwwe08090809",
    "wayneradiotv",
    "VitalikihCrypto",
    "PokemonTCG",
    "VitalikqkCrypto",
    "ChessKid",
    "Froggen",
    "mhwatson",
    "Leopard",
    "bui_oihing",
    "Jensen",
    "Macey_Dawns",
    "pinkcatbad",
    "Lobanjicaa",
    "Max_Fewtrell",
    "Twitch_ANZ",
    "elfYou",
    "JohnnyBoi_i",
    "Rolinsix",
    "mang0",
    "KhaosAdam",
    "Vitalik_ETH66",
    "xzact",
    "chibidoki",
    "Xaryu",
    "BorderlineEntertainment",
    "VitalikrhETH",
    "WavePunk",
    "Razer",
    "Vitaliksom_ETH",
    "PandaCup2",
    "jeffgerstmann",
    "haechanlover3000",
    "Vitalikcq_ETH",
    "officialmikemc",
    "VitalikVTButerin",
    "Erika_Bones",
    "VitalikvvCrypto",
    "VitalikKOButerin",
    "stay_podomatjelly8",
    "Victor",
    "iLLeYY",
    "Chloe_Zasing",
    "CobaltStreak",
    "seonghwazip",
    "Vitalikiq_Invests",
    "Diablo",
    "PSZilean",
    "Vitalik_EventsEG",
    "amustycow",
    "Pyrocynical",
    "Rebecca_Rmber",
    "emilyywang",
    "72hrs",
    "JOEYKAOTYK",
    "HarryHesketh",
    "yourmugglestore",
    "deardejun",
    "Vitalikas_Invests",
    "moonstudio_en",
    "TPAIN",
    "Rebecca_Mmber",
    "VitalikXYButerin",
    "jorbs",
    "DizzyKitten",
    "Vitalikbe_ETH",
    "mxmtoon",
    "Daisy_Gatts",
    "Chap",
    "EliraPendora",
    "Vitalikat_Crypto",
    "Vitalik_EventsWW",
    "Sajam",
    "GeT_RiGhT",
    "VaatiVidya",
    "VitalikmfCrypto",
    "Vitalik_ETH10",
    "itmeJP",
    "MrMoonsHouse",
    "TommyKayLIVE",
    "Luna_Vitters",
    "shhitsasecretiykyk",
    "NinaKosaka",
    "Kate_Qawns",
    "btssmash4",
    "WooxSoloant",
    "Vitalikpg_Crypto",
    "RubberRoss",
    "Axielnfinitybqi",
    "FootballManager",
    "riotgamesar",
    "Zfg1",
    "solarblues2",
    "clashofthestars1",
    "LollaEnVivo27",
    "Destroy",
    "JERICHO",
    "EdenEsports",
    "wtf1official",
    "SnipingSoup",
    "allkeyshop_tv",
    "kyliebitkin",
    "jingggxd",
    "Erika_Mones",
    "VitalikjxETH",
    "M1kyx",
    "AlbanKnox",
    "Macey_Jawns",
    "amekassa",
    "Officialf0rest",
    "VitalikrsCrypto",
    "dellor",
    "Dakotaz",
    "vipie2000",
    "CCT_EN2",
    "erowtv20",
    "Leena",
    "SecretSleepoverSociety",
    "Tanya_Kenton",
    "DiscotekMedia",
    "alphataurif1",
    "XQN_TheSad",
    "Kandyland",
    "Betty_Oatilda",
    "BaylenLevine",
    "DashCamOwnersAus",
    "Rose_Yatts",
    "Vitalik_EventsFU",
    "slimeIRL",
    "Replays",
    "WSDMgaming",
    "Daisy_Tatts",
    "saranghae17",
    "Grimmmz",
    "Vitalik_ETH83",
    "VitalikuuCrypto",
    "pnkysparkles69",
    "Paige_Ziggs",
    "Vitalik_ETH47",
    "Luna_Hitters",
    "Stacey_Ariggs",
    "AnnaCramling",
    "Stodeh",
    "Spicalol",
    "bigdumbgaming",
    "Crypto_Vitaliksx",
    "CrReaM",
    "EliteDangerous",
    "PokemonUNITE",
    "JonBams",
    "Emma_Lones",
    "WiLLiS",
    "Loserfruit",
    "JohnWolfe",
    "XcaliburYe",
    "TheRSGuyple",
    "Beaulo",
    "AxieInfinityaa",
    "Kotton",
    "Surefour",
    "WooxSologul",
    "RewackOP",
    "adeptthebest",
    "TwitchToronto",
    "queensgg",
    "Incon",
    "LobosJr",
    "Heelmike",
    "juanflatroo",
    "LollaEnVivo13",
    "Vitalikfy_Foundation",
    "Liam",
    "BLOU",
    "CEOGaming",
    "kyootboss",
    "iamcougo",
    "CCT_EN3",
    "ProtonJon",
    "Vitalik_ETH91",
    "bokoen",
    "NLCLoL",
    "gamesweekberlin",
    "Vitalik_EventsVA",
    "ScammerPayback",
    "aesobts",
    "loveislanduknosub",
    "sylveey",
    "akaNemsko",
    "VitalikGMButerin",
    "Vitalikbj_Invests",
    "Elspeth",
    "Kxpture",
    "Gingy",
    "levinsrr",
    "Vitalikgo_Buterin",
    "Vitalikda_Foundation",
    "Avast",
    "Kacey_Uetrova",
    "VitalikijCrypto",
    "Vitalikxt_Invests",
    "CrazySlick",
    "d0cc_tv",
    "ThinkingToMuch",
    "Bigpuffer",
    "cerclemusic",
    "Zemie",
    "NEWSTATEMOBILE",
    "nerdstreet",
    "Memeio",
    "PhilzALT",
    "Vitalikhi_Foundation",
    "kevinmartin",
    "eaJParkOfficial",
    "Dayna_Lawns",
    "TheRSGuyxcj",
    "Syndicate",
    "NumotTheNummy",
    "logic",
    "CasinoDaddy",
    "mynameisGRiZ",
    "HSU_LIVE",
    "AxieInfinityqs",
    "MASL_soccer",
    "rayditz",
    "Vitalikgo_Crypto",
    "FMStreamerShowdown",
    "WooxSolobbp",
    "Keife_",
    "Purplecliffe",
    "Nick28T",
    "Expicifed",
    "Axielnfinityrrm",
    "gxrardvb",
    "Tanya_Hills",
    "Weak3n",
    "MANvsGAME",
    "BazzaGazza",
    "DreamHackCS2",
    "anna_paull",
    "XurWatch",
    "Meowko",
    "RealzBlueWater",
    "CompletedItMate",
    "KingOfTheDot",
    "AxieInfinityif",
    "solarbacca",
    "YamatosDeath1",
    "nmplol2",
    "Kate_Kawns",
    "VitalikwiETH",
    "watchmeblink",
    "girl_dm_",
    "superleague",
    "spoopykitt",
    "Brittt",
    "TiptoeTingles",
    "AxieInfinitysy",
    "rprx",
    "DWPresents",
    "VitaliksrCrypto",
    "Vitalikci_Foundation",
    "Dayna_Bawns",
    "ESL_Australia",
    "Nidas",
    "Tilly_Kawns",
    "Kate_Vawns",
    "HBomb94",
    "mrgamingmlb1",
    "ScottJund",
    "VitaliknsCrypto",
    "ProdigyDDK",
    "Mirlolxd",
    "osulive",
    "Tanya_Genton",
    "VitalikrjCrypto",
    "Rose_Matts",
    "KristoferYee",
    "Vitalik_ETH73",
    "AxieInfinitybb",
    "VitalikButerinjn",
    "PhlyDaily",
    "kurt0411",
    "MandaloreGaming",
    "awayfromhomestreaming",
    "AxieInfinityzu",
    "ESLtv",
    "Tanya_Aenton",
    "Lucy_Ailliams",
    "JoshOG",
    "MFAMGauntlet",
    "bannabumatee",
    "TeosGame",
    "PYKA",
    "luvkristeen",
    "Tia_Icotts",
    "traphitss",
    "Vitalikke_Foundation",
    "verhulst",
    "VitalikPFButerin",
    "ZeaIand",
    "Dayna_Eawns",
    "Crypto_Vitalikmh",
    "Rose_Hatts",
    "SNKofficial",
    "qullamaggie",
    "AxieInfinityhl",
    "SayeedBlack",
    "VitaliktbCrypto",
    "Vitalik_ETH50",
    "Arsenal",
    "Vitalikui_Invests",
    "Carmen",
    "VitalikymETH",
    "shofu",
    "joinRED",
    "VitalikButerinat",
    "volleystream84",
    "Vitalikwu_Invests",
    "Fairlight_Excalibur",
    "PlatChatPodcast",
    "UMGGaming",
    "Posty",
    "AxieInfinityub",
    "morbius247returns",
    "AsmodaiTV",
    "Vitalikix_Crypto",
    "lonelobospodcast",
    "FaZeSway",
    "GCDTV",
    "SheriffEli",
    "TheDanDangler",
    "Murda",
    "MisterVoidBR",
    "Vitalikzt_Invests",
    "littlelianna",
    "AxieInfinityii",
    "WARRIORRUST",
    "Emma_Aones",
    "Klean",
    "BBLiveTamil",
    "SimCopter1",
    "Tanya_Xenton",
    "Macey_Zawns",
    "shigetora",
    "Porsche",
    "Vitalik_ETH3",
    "Becca_Kichmond",
    "missmafiaxx",
    "Kruzadar",
    "Trickywi",
    "DarkViperAU",
    "NerdStreetD",
    "chrissyofficial",
    "FIBA",
    "officialmuneydre",
    "Vitalik_ETH0",
    "kennybeats",
    "LSV",
    "cessstr_",
    "Vitalikgz_Invests",
    "aspiringspike",
    "KingGeorge",
    "Trey24k",
    "NoriyaroJapan",
    "PGL_DOTA2EN3",
    "Warcraft",
    "Vitalikbr_Buterin",
    "OMEN",
    "MultiVersus",
    "Xposedjs",
    "maskenissen",
    "Topsonous",
    "RLEsports",
    "testptd",
    "Pestily",
    "Gamers8GG_b",
    "Tfue",
    "BrawlStars",
    "Quin69",
    "danaterrace",
    "Swagg",
    "scump",
    "DotEsports",
    "fuslie",
    "bellapoarch",
    "Vitalikbo_Crypto",
    "Olivia_Uallis",
    "tuanzy",
    "Doublelift",
    "zackrawrr",
    "ironmouse",
    "WikiSellow",
    "manuelperera19",
    "SamsungUS",
    "evo3",
    "Maximilian_DOOD",
    "ATT",
    "forsen",
    "pamibabyy",
    "event_live",
    "Xposedtn",
    "TinaKitten",
    "Olivia_Nallis",
    "gia_lynn",
    "current",
    "Jankos",
    "ShahZaM",
    "ESL_Dota2b",
    "Duke",
    "BigGuy",
    "Shocktii",
    "Amouranth",
    "gamescom",
    "HS_lives",
    "CDawgVA",
    "MonsterEnergy",
    "VitalikmbETH",
    "inexoverse2",
    "Twitch",
    "CohhCarnage",
    "smtown_official",
    "PENTA",
    "NiKo",
    "Hiko",
    "Mary_Down",
    "Fresh",
    "Flight23white",
    "Vitalik_ETH26",
    "ESL_CSGOb",
    "PCGamer",
    "DrLupo",
    "VitalikevETH",
    "tw1cetour",
    "streamblackswan12",
    "Z_Laner",
    "nyanners",
    "Vitalikpl_Crypto",
    "GMHikaru",
    "landonorris",
    "veibae",
    "ryeonggu_01",
    "Olivia_Rallis",
    "Xposedbm",
    "caps",
    "F1Manager",
    "RoobetESPORTS_2",
    "michaelclifford",
    "jamsjam1",
    "shinybang1",
    "EUMasters",
    "Mongraal",
    "Xposedqi",
    "Kitboga",
    "ClintStevens",
    "MrSavage",
    "100Thieves",
    "Macey_Sawns",
    "Xposedgs",
    "CapcomFighters",
    "Rustafied",
    "CORINNAKOPF",
    "Maya",
    "LDShadowLady",
    "sweetdreams",
    "GloriaMatvien",
    "Hitch",
    "soyabeannyy",
    "Vitalikby_Crypto",
    "LollaEnVivo24",
    "CoffeeStainStudiosDevs",
    "blameF",
    "AfroSenjuTV",
    "Trick2g",
    "Tilly_Zawns",
    "AxieInfinitysw",
    "Axielnfinityelh",
    "Momo",
    "AxieInfinityyz",
    "TSM_Viss",
    "Linkus7",
    "Kate_Oawns",
    "Vitaliktz_Crypto",
    "kalynnkoury",
    "Wholesome_Games",
    "ParamountPlus",
    "kierapleaze",
    "LollaEnVivo12",
    "JakePaul_vs_Woodley_TV1",
    "WooxSoloepb",
    "Rose_Gatts",
    "VitalikbrCrypto",
    "ops1x",
    "YouAreRAD",
    "Whaazz",
    "Brofain",
    "Dayna_Cawns",
    "smooyacs",
    "GMBenjaminFinegold",
    "djrayraytaiwan",
    "rflstrdonda",
    "Jodie_Xryan",
    "Vitaliklr_Invests",
    "CaptainSparklez",
    "Wardiii",
    "Lucy_Oilliams",
    "SR_Kaif",
    "BigIraq",
    "SamSaberi",
    "Minion777",
    "GunnarDotA2",
    "travpiper",
    "PearlescentMoon",
    "Daisy_Matts",
    "Vitalikxw_ETH",
    "itsmaralee",
    "WILDCAT",
    "duolingo",
    "Vitalikpr_Foundation",
    "McCreamy",
    "Pikabooirl",
    "Chloe_Gasing",
    "VitalikamCrypto",
    "VitalikzdCrypto",
    "Vitalikbt_Foundation",
    "AYYJAYY",
    "ggGibi",
    "Imgur",
    "freyzplayz",
    "Vitalikzu_Crypto",
    "tftriotgames",
    "renjunsuh",
    "CONEY",
    "SourSweet",
    "Vitalikgx_Crypto",
    "Dayna_Oawns",
    "bigdaddysammy0615",
    "antdavis3",
    "Dayna_Yawns",
    "Daisy_Yilliams",
    "Daisy_Patts",
    "Back2Warcraft",
    "Vitalikfw_Buterin",
    "WackyJacky101",
    "FrtingGlitter",
    "JW1337",
    "fuji720x",
    "AndyMilonakis",
    "Spaceboy",
    "MTashed",
    "Berticuss",
    "CalebDMTG",
    "MrTLexify",
    "Vitalik_ETH44",
    "foodbeast",
    "chessbrah",
    "Daisy_Fatts",
    "VitalikButerinbh",
    "Drakensang",
    "KayakR6",
    "PSLPUBG",
    "Vitalik_ETH7",
    "Sick_Nerd",
    "jaystreazy",
    "Vitalikfr_Invests",
    "imjasmine",
    "SCUMgame",
    "Zeldathon",
    "DaddyDimmuTV",
    "Jodie_Oryan",
    "CrankGameplays",
    "PlayStation",
    "Vitalikvz_Crypto",
    "oney",
    "EvenMatchupGaming",
    "FIFAe",
    "Vitalikqv_Foundation",
    "nwslofficial2",
    "WooxSolozwv",
    "TheRSGuykta",
    "VitalikicCrypto",
    "MidOne",
    "LuckyGhost",
    "WooxSoloizr",
    "Anthony_Kongphan",
    "bubb4bot",
    "VitalikSEButerin",
    "BLASTtv",
    "Vitalik_ETH78",
    "Oatsngoats",
    "TeamBeyondnet",
    "Cryocells",
    "GratisStatus",
    "hjyjmjaydhjjtrsr",
    "Tiametmarduk",
    "VitalikmmCrypto",
    "Naguura",
    "GrandPooBear",
    "Darling",
    "AEWGames",
    "TheRSGuyuzl",
    "Crystalst",
    "Merk",
    "VitalikVUButerin",
    "Kiaraakitty",
    "WooxSolozxc",
    "VitalikksCrypto",
    "Vitalikxz_Buterin",
    "Kasparovchess",
    "Tanya_Oenton",
    "NotAestheticallyHannah",
    "Mendo",
    "chess24",
    "cdewx",
    "Robbaz",
    "rosemilovelock",
    "EliGE",
    "EpulzeGaming",
    "FoxenKin",
    "LongShot",
    "goldencloset13",
    "theheavynetwork",
    "VitalikdyCrypto",
    "LGLOYAL",
    "wudijo",
    "Kaellyn",
    "piso4",
    "BoomerNAlt",
    "pilavpowa",
    "KatEvolved",
    "ETH_Vitalikdc",
    "JesseCox",
    "MembTV",
    "apparentlyjack_rl",
    "Badlinu",
    "Vitalikbc_ETH",
    "Tilly_Lawns",
    "imrosen",
    "FORG1VENAPM",
    "VitalikfrCrypto",
    "Shiphtur",
    "Sekapoko",
    "y8official",
    "TSM_Reps",
    "AxieInfinityzz",
    "VitalikjpCrypto",
    "teleperformance_group",
    "FIRSTinspires_Carver",
    "Chloe_Uasing",
    "Nogla",
    "Xeppaa",
    "WooxSoloaix",
    "VitalikswETH",
    "SLANDER",
    "LatinaAngel23",
    "Jabroni_Mike",
    "TaeTae_Feeds",
    "Biotoxz_",
    "na3vis",
    "Axielnfinitypzo",
    "Doggydogg20",
    "MiltonTPike1",
    "Reetlol",
    "zipelCS",
    "FaZeKaysan",
    "Randolph",
    "KatsumiFPS",
    "LordAethelstan",
    "DreamHackHS",
    "OLESYALIBERMAN",
    "twitchmusic",
    "Chloe_Tasing",
    "AmeliaGurl4",
    "Gdsandstorm",
    "DyaRikku",
    "ThinkingMansValo",
    "ispuuuv",
    "JoshStrifeHayes",
    "vgbootcamp3",
    "ErynStreams",
    "Zapman",
    "DooleyNotedGaming",
    "kyeos99",
    "Alkaizerx",
    "gloot_apex",
    "Bexuki",
    "Mmorpg",
    "nickgreen12",
    "FlaccidBaron",
    "VitaliktCrypto",
    "shingekinoluan",
    "imPROBZZ",
    "BakeeZy",
    "subliners",
    "Lucy_Silliams",
    "TheNicoleT",
    "jpctheman_",
    "ICPnetwork",
    "newworldordershow",
    "multistanid",
    "HermanLi",
    "EXBC",
    "firstaews",
    "ArmyEntertainment",
    "heyimbee",
    "TheBubbaArmy",
    "phoodu",
    "soulightnin",
    "daireb",
    "itsSpoit",
    "Kate_Cawns",
    "ImMarksman",
    "Raxxanterax",
    "ZeRoyalViking",
    "420jenkins",
    "Dayna_Gawns",
    "FrankiesHideout",
    "caitibugzz",
    "chanpoolsimp1",
    "CookieLoLxx",
    "littlemochii_",
    "Vitalikux_Invests",
    "worldfut",
    "JoJoThaMoFo",
    "AxieInfinitycx",
    "BATTLEFIELD",
    "flamuu",
    "YogCon",
    "mundohockey1",
    "BananaSlamJamma",
    "FerrariEsports",
    "Dayna_Hawns",
    "WoolieGaming",
    "DotoDoya",
    "BobbyPoffGaming",
    "bbunoob",
    "LaynaLazar",
    "VitalikButerinvf",
    "Pint",
    "Kate_Ymith",
    "bmkibler",
    "BagginsTV",
    "Antfrost",
    "Rose_Catts",
    "HyperRatTV",
    "setsukotft",
    "Tylerootd",
    "MadCityGG",
    "metagame",
    "Axielnfinitynkq",
    "Vitalikma_Buterin",
    "Apryze",
    "Dayna_Kawns",
    "Paryeet",
    "Vitalik_ETH15",
    "thealchemyths",
    "CMZGGs",
    "plushys",
    "Xisuma",
    "KLO25",
    "tenomedia",
    "trent_fps",
    "Stacey_Eriggs",
    "raphael97410",
    "OuterHeaven",
    "TipoftheHats",
    "Kurzgesagt_official",
    "Dignitas",
    "bbreadman",
    "LeeandLie",
    "Vitalikxe_Crypto",
    "ms_event1",
    "IFrostBolt",
    "elirymagee",
    "Faith",
    "CurtisRyan",
    "loveforenhypenn",
    "WorldWideWob",
    "Keyorii_NA",
    "WagamamaTV",
    "bobqinxd",
    "Vitalikxg_Foundation",
    "Ephey",
    "VitaliknoETH",
    "sukiyuki3",
    "Axielnfinityhgt",
    "VitalikNNButerin",
    "PorterRobinson",
    "Kenji",
    "Peeve",
    "marcrebillet",
    "AnneMunition",
    "JadetheJaguar",
    "MyztroGaming",
    "VitalikmeETH",
    "MBTYuGiOh",
    "Guzu",
    "dubbs33",
    "Vitalik_ETH31",
    "Vitalikry_Invests",
    "e_seoa",
    "Sjow",
    "Mantis",
    "Vitaliksy_Crypto",
    "Vitalikuv_Invests",
    "StreamerHouse",
    "Vitalikli_Crypto",
    "VitalikButerinre",
    "RetroGaijin",
    "AxieInfinityny",
    "VitalikciCrypto",
    "Gutfoxx",
    "jennmcallister",
    "NerdStreetA",
    "Chloe_Kasing",
    "Chloe_Easing",
    "VitalikvjETH",
    "Paige_Qiggs",
    "Knut",
    "Aphromoo",
    "SuperEvan",
    "Arthars",
    "SimpleFlips",
    "Jukeyz",
    "UniRocketeers",
    "Vitalikap_Crypto",
    "WooxSolovkh",
    "TBJZL",
    "Tanya_Gills",
    "VitalikButeriniq",
    "TwoSync",
    "SideLogic",
    "TSM",
    "Vitalikhv_Crypto",
    "Ezekiel_III",
    "Yogscast",
    "Scrub",
    "1013dagod",
    "pekeasmr",
    "VitalikfCrypto",
    "Betty_Natilda",
    "Vitalik_ETH48",
    "Arex",
    "Marved6",
    "Anna_Chess",
    "Syztmz",
    "Paige_Kiggs",
    "khleothomas",
    "supercorp1994",
    "Xbox",
    "Mindcrack",
    "CallMeCarsonLIVE",
    "Lucy_Villiams",
    "Chloe_Basing",
    "FenoHS",
    "Vitalikgy_Crypto",
    "Kate_Pawns",
    "Dakillzor",
    "Acie",
    "BlackDesertConsole",
    "soshidani",
    "MattHDGamer",
    "Hotdubtimemachine",
    "ourmagicshop2",
    "ETH_Vitalikbw",
    "DanGheesling",
    "NorthernArena",
    "WooxSololmw",
    "Vitalikpb_Buterin",
    "Seapeekay",
    "BuffPup",
    "ETH_Vitalikzy",
    "Crypto_Vitalikgz",
    "DolphinChemist",
    "NeebsGaming",
    "AxieInfinityqd",
    "iyouxin",
    "JordanFisher",
    "Vitalikux_Crypto",
    "Meteos",
    "WhiteBoyMaj",
    "Governor",
    "WooxSolokjb",
    "Wowhead",
    "Luciid_TW",
    "CheekyGamblers",
    "armaplatform",
    "lol_selfmade",
    "WooxSolozpm",
    "InsightOnEsports",
    "Ziqoftw",
    "FIRSTinspires_Galileo",
    "quqco",
    "GearsforBreakfastOfficial",
    "ofmanny",
    "NateHill",
    "Dexbonus",
    "BonamantTV",
    "dubs",
    "tommyunold",
    "duelbits",
    "UFOs",
    "Chenzo",
    "VenusWorld",
    "bunny_gif",
    "Jynxzi",
    "Tommey",
    "KindaFunnyGames",
    "ioplup",
    "113bumm",
    "Rose_Iatts",
    "VitalikjhETH",
    "Vitaliklt_Foundation",
    "HeroMarine",
    "FossyGFX",
    "JakePaul_vs_Woodley_TV5",
    "keaiduo7",
    "Jay3",
    "WooxSoloyxn",
    "Betty_Catilda",
    "Axielnfinityfrw",
    "Vitalikol_ETH",
    "themcyum",
    "WooxSolozut",
    "Vitalikdt_Foundation",
    "itswill",
    "iambizy",
    "bebe872",
    "SC2ByuN",
    "lelisdota",
    "supercatkei",
    "Millie_Criggs",
    "Lava_Flame2",
    "eltiowwe",
    "Maakep",
    "VitalikxcCrypto",
    "IndyAChallenge",
    "Axielnfinitybfn",
    "Gigz",
    "JGOD_Gaming",
    "TheRSGuyrex",
    "VitalikButerinha",
    "quartzJ0G",
    "Rainhoe",
    "seoahtv",
    "VitalikstCrypto",
    "clintonsparks",
    "keixt_",
    "AxieInfinityrk",
    "eSportsBlink",
    "Yuzu",
    "VitalikpnCrypto",
    "PeteZahHutt",
    "shutbloodki",
    "VitaliknfETH",
    "VitaliklmCrypto",
    "RayAkaOG",
    "Nalopia",
    "FinanaRyugu",
    "Lucy_Tilliams",
    "Crayator",
    "MajinPhil",
    "Tanya_Mills",
    "WooxSoloyli",
    "Vixella",
    "MMG69",
    "chesscomlive",
    "TheRSGuyobj",
    "VitalikqwCrypto",
    "VitalikqmCrypto",
    "Vitalikah_Invests",
    "Cimoooooooo",
    "PokerStars",
    "Redshell",
    "WooxSoloolp",
    "Lumituber",
    "Wolfiez",
    "Northwar",
    "EddieChestnut",
    "lnfraction",
    "Vitalik_ETH61",
    "Vitalikag_Crypto",
    "Crimsix",
    "WooxSolorms",
    "EvaCudmore_",
    "littlethingsmingle",
    "VitalikbxCrypto",
    "DreamHackFN",
    "Complex",
    "EmilShe1n",
    "DeMusliM",
    "BTNeandertha1",
    "Disclosure",
    "TheBlackHokage",
    "JaboodyShow",
    "itsvaydra",
    "VitalikgiETH",
    "mrgirlreturns",
    "ROBN",
    "vitalikkkcrypto",
    "Odoamne",
    "lilypi2",
    "nwslofficial4",
    "futsextv",
    "Shamona1",
    "blaber",
    "Emma_Dones",
    "Lucy_Zilliams",
    "WooxSoloxib",
    "ortoPilot",
    "IreliaCarriesU",
    "FIRSTinspires_Newton",
    "lindseystirling",
    "datafolders",
    "gflipmusic",
    "Bloodhuntgame",
    "VitalikghCrypto",
    "LuckyChamu",
    "Sp4zie",
    "Macey_Iawns",
    "mohamedlightcr",
    "Vitalikvz_Invests",
    "FIRSTinspires_Roebling",
    "AxieInfinityhbu",
    "Methodz",
    "Ninjayla",
    "lolpacific",
    "angryginge13",
    "Spammiej",
    "WooxSolonfh",
    "TrumpSC",
    "SoloRenektonOnly",
    "JokerTheAnarchist",
    "fanfan",
    "Lourlo",
    "mrekkosu",
    "OfficialYuGiOhTCG",
    "NerdStreetB",
    "VitalikjsETH",
    "VitalikwcCrypto",
    "Rose_Ratts",
    "dejivswassabi1",
    "LollaEnVivo14",
    "AnnieFuchsia",
    "Hitchariide",
    "GeeksEh",
    "ryukahr",
    "TeamRedline",
    "negaoryx",
    "felixcartal",
    "WooxSolokcv",
    "EUROVISION2022",
    "Cowsep",
    "Flakes",
    "Raeyei",
    "WolfeyVGC",
    "jaquesesmith",
    "NaomiKyle",
    "Dayna_Fawns",
    "Oatley",
    "joeb5",
    "katelovesihop",
    "Sliggytv",
    "Vitalik_EventsTJ",
    "physicalgamerz",
    "lilyachty",
    "AirForceGaming",
    "VitalikohCrypto",
    "Celerity",
    "BAFTA",
    "ScarlettM",
    "picNICKbasket",
    "Jimmy_Broadbent",
    "twitchultimateroyale_2021",
    "Prefoxfox",
    "Yoclesh",
    "BoomTV",
    "Millie_Xriggs",
    "yamsllama",
    "djkbun",
    "yumytv",
    "TheRedW",
    "PMoney",
    "AxieInfinityee",
    "Moose_Taffy",
    "Knights",
    "Rose_Vatts",
    "Wingsofdeath",
    "Neenoh",
    "itsJerian",
    "MelbourneLive",
    "VitalikptCrypto",
    "GlobalTimeAttack",
    "MARI",
    "StreamQueens",
    "TheRSGuylck",
    "TheCompletionist",
    "Evample2",
    "PotasticP",
    "dizzy",
    "valorantesports4",
    "ESL_SC2",
    "STPeach",
    "a_couple_streams",
    "VitalikskETH",
    "ESEA",
    "VitalikbpCrypto",
    "Vitalikxp_Buterin",
    "Vitalikdf_Crypto",
    "Matimi0",
    "rendogtv",
    "ExcessiveProfanity",
    "WooxSolodht",
    "VitaliknCrypto",
    "thecybermentor",
    "ibLue",
    "Kate_Uawns",
    "AxieInfinitynx",
    "resolut1ontv",
    "PurgeGamers",
    "DATAFGC",
    "FriendsAtTheTable",
    "Elosanta",
    "Vitalikvn_Invests",
    "Jodie_Wryan",
    "OfficialMikeShinoda",
    "AxieInfinityti",
    "LilAggy",
    "clairytale",
    "dubudota",
    "visionjaeh",
    "hitsquadgodfather",
    "ToysForBobOfficial",
    "GD_Booya",
    "VitalikwhCrypto",
    "souljaboy",
    "Halocene",
    "lifeofgman",
    "Dayna_Zawns",
    "Pengu",
    "Jack",
    "Nika",
    "Sigma",
    "foundeth",
    "Valeria7K",
    "kckjthesecond",
    "SZ_Taisheen",
    "VitalikttCrypto",
    "zaayonyt",
    "ModestPelican",
    "eth_found",
    "iGotUrPistola",
    "JASONR",
    "highrollersdnd",
    "SwizzMB",
    "schrodingerLee",
    "Vitalikdl_Crypto",
    "DirtyDan79",
    "SabeRLighT00",
    "빢유환 (yuhwanp)",
    "juventus",
    "VitalikButerinlc",
    "SirhcEz",
    "VitalikrCrypto",
    "iziprime",
    "AsunaWEEB",
    "sumayyl",
    "Rush",
    "sinatraa",
    "Chess",
    "PUBG_BATTLEGROUNDS",
    "tofumisoya",
    "boomrecords",
    "Vitaliksu_Crypto",
    "RocketLeagueOCE",
    "ullillsl",
    "Xposedvm",
    "Elajjaz",
    "JackManifoldTV",
    "Netflix",
    "BadBoyHalo",
    "richwcampbell",
    "kkatamina",
    "Armamental",
    "Vitalikua_Crypto",
    "Vitalikdq_Crypto",
    "benjyfishy",
    "Maximum",
    "Caedrel",
    "govballnyc",
    "Northernlion",
    "iliketheviewrightnow",
    "EMGesports1",
    "Mary_Aown",
    "DE_Steve",
    "AdmiralBahroo",
    "RedBull",
    "Otzdarva",
    "BotezLive",
    "Foolish_Gamers",
    "BoweryPresents",
    "Stylosa",
    "Xposedcv",
    "evaanna",
    "VitalikthCrypto",
    "ScreaM",
    "ksilittlebrotherfight",
    "SypherPK",
    "Vitalikzm_Crypto",
    "NASA",
    "ShivFPS",
    "Nintendo",
    "cloakzy",
    "Aydan",
    "sopeviiie",
    "Kyle",
    "hyunnie123",
    "twitchgaming",
    "Im_Dontai",
    "ggloveskirsten",
    "skeppy",
    "MitchJones",
    "HondaDreamLab",
    "lilypichu",
    "FabrizioRomano",
    "Punz",
    "lostlands",
    "TrueGeordie",
    "emilyghoul",
    "berleezy",
    "ChilledChaos",
    "39daph",
    "Xposedht",
    "Rose_Xatts",
    "DeadByDaylight",
    "metaquest",
    "Magic",
    "Xposedhl",
    "SmallAnt",
    "Dkayed",
    "TheDivisionGame",
    "m0NESYoF",
    "ramzes",
    "dojacattington",
    "Vitaliktj_Crypto",
    "VitalikltCrypto",
    "GimR",
    "NickEh30",
    "AnthonyZ",
    "CD PROJEKT RED",
    "runthefutmarket",
    "EsfandTV",
    "daltoosh",
    "dunkstream",
    "TeamLiquid",
    "Subroza",
    "RDCgaming",
    "pokelawls",
    "vanseurope",
    "PlayLostArk",
    "Stewie2K",
    "Xposedqv",
    "Method",
    "LosPollosTV",
    "xposedvf",
    "RATIRL",
    "SurviveTheARK",
    "jjongribo",
    "Symfuhny",
    "kripto_future",
    "AxieInfinityof",
    "AyeZee",
    "QTCinderella",
    "DiazBiffle",
    "Fundy",
    "NeoTokyo",
    "bakingwithnct",
    "SicK_cs",
    "Vitalikaq_Foundation",
    "watsonamelia_hololiveen",
    "aquwuila",
    "QuarterJade",
    "GoodTimesWithScar",
    "nl_Kripp",
    "minunivers",
    "imls",
    "Emma_Vones",
    "HitPointOne",
    "Silky",
    "Stacey_Driggs",
    "Macey_Fawns",
    "ArtificialNext",
    "BlockchainGameGang",
    "Olivia_Gallis",
    "Becca_Jicks",
    "ssujams1",
    "Vitalikwm_Crypto",
    "Vitalikrg_Foundation",
    "boxbox",
    "parfaxgaming",
    "stableronaldo",
    "billzo",
    "Gigguk",
    "NBA_TopShot",
    "hwafairys",
    "philgodlewski",
    "seungsibot",
    "dwjft",
    "mfsoob",
    "hamsterjinn",
    "TFBlade",
    "syriohannie",
    "Wirtual",
    "PlayNewWorld",
    "Takyn",
    "zanyjww",
    "minieloops",
    "s0mcs",
    "DeuceAce",
    "shxtou",
    "HusKerrs",
    "esportsawards",
    "Nihachu",
    "youyoukth",
    "Vitalikks_Foundation",
    "PWRDEsports1",
    "Rebecca_Amber",
    "W2S",
    "Tectone",
    "Jinnytty",
    "WorldofTanks",
    "Drututt",
    "AussieAntics",
    "GTAWiseGuy",
    "xNestorio",
    "AmazonMusic2",
    "zAAzturkie",
    "AdmiralBulldog",
    "opry_official",
    "midbeast",
    "Distortion2",
    "Mia_Fcotts",
    "Erika_Lones",
    "Jagex",
    "Daisy_Batts",
    "RollingLoud",
    "sunburnnnn_",
    "Aflac",
    "Becca_Vicks",
    "TeeGrizzley",
    "jidionpremium",
    "Star Citizen",
    "masondota2",
    "Alinity",
    "dogdog",
    "nwslofficial",
    "Diegosaurs",
    "HLTVorg",
    "ESL_DOTA2",
    "OldSchoolRS",
    "BigBossBoze",
    "Rebecca_Kmber",
    "Saber",
    "its_iron",
    "LuluLuvely",
    "TwitchSports",
    "fsofiy",
    "x2Twins",
    "Slimecicle",
    "blueriboo",
    "SMii7Y",
    "Xposedwl",
    "NavyMWR",
    "ethfound",
    "gobbot64",
    "Nadeshot",
    "AbdulHD",
    "Thijs",
    "perkz_lol",
    "twcpalooza",
    "NBA2KLeague",
    "minbinseung",
    "FanumTV",
    "OTKnetwork",
    "LarianStudios",
    "Faide",
    "xqcisoffline",
    "TeePee",
    "Becca_Wicks",
    "Vitalikfc_Foundation",
    "Vinesauce",
    "cxmmunity",
    "wossythings",
    "awesamdude",
    "IWDominate",
    "funnyhoodvidztv",
    "w33haa",
    "Enviosity",
    "ksonsouchou",
    "Bugha",
    "VitalikwCrypto",
    "DragonBallFighterZ",
    "astravsmezi",
    "SonySanDiegoStudio",
    "cyr",
    "evo6",
    "Vitalikqh_Crypto",
    "ggukiebear7",
    "GeneralSam123",
    "koil",
    "RTGame",
    "desertbus",
    "ZealsAmbitions",
    "Pieface23",
    "KingGothalion",
    "Macey_Cawns",
    "DougDougW",
    "Smoke",
    "floofyeosang",
    "lookingforyeo",
    "Rainbow6Bravo",
    "WooxSolo",
    "skippypoppin",
    "snuffy",
    "lilsimsie",
    "hypeirun",
    "paperairplane456",
    "ROGTournament",
    "QuickyBaby",
    "Insym",
    "GothamChess",
    "ArcSystemWorksU",
    "Whippy",
    "RduLIVE",
    "NiceWigg",
    "LCO",
    "Vitaliktk_Crypto",
    "T90Official",
    "Yassuo",
    "MystaRias",
    "Hanssama",
    "McconnellRet",
    "Xposed",
    "PlayHearthstone",
    "pavithranisi",
    "nAts",
    "hJune",
    "Atrioc",
    "Willjum",
    "yayster",
    "miniminter",
    "highleaguefree",
    "ddeonusaur",
    "PandaCup",
    "lol_nemesis",
    "hypeirun1",
    "VitalikYZButerin",
    "Kiyoon",
    "qojqva",
    "Tomato",
    "UberHaxorNova",
    "Masayoshi",
    "LatinUp",
    "TaySon",
    "GrubhubGaming",
    "WARDELL",
    "Dendi",
    "itsaschoolnight",
    "Vitalikyh_ETH",
    "2GGaming",
    "B0aty",
    "erobb221",
    "Vitalik_ETH72",
    "Rogue",
    "DannehTV",
    "GingiTV",
    "BlackDesertGame",
    "Xposedia",
    "VarietyisHOPE",
    "VonDice",
    "aimsey",
    "Towelliee",
    "Kai11xirving",
    "Akademiks",
    "highleaguezadarmo",
    "evo7",
    "backfischmayo",
    "AvoidingThePuddle",
    "Mystakimyst",
    "kyootbot",
    "NRGgg",
    "Vitalik_EventsZJ",
    "willneff",
    "NortonGaming",
    "Shylily",
    "supertf",
    "Zentreya",
    "Vitaliktr_Buterin",
    "GWBPS_en",
    "Rebecca_Umber",
    "teIIstroy",
    "Myth",
    "Frost_",
    "CallMeKevin",
    "PontiacMadeDDG",
    "HealthyGamer_GG",
    "Ray__C",
    "tae_meow_gi",
    "roflgator",
    "nba2k",
    "A_Seagull",
    "moonduckTV",
    "antoineah2020",
    "eltiovitoxwwe",
    "Vitalik_EventsLI",
    "zai",
    "The_Happy_Hob",
    "Greekgodx",
    "timetotwice87",
    "Vitaliknt_Foundation",
    "Silvervale",
    "Annoying",
    "Cr1tdota",
    "evo4",
    "uhSnow",
    "ToryLanez",
    "T0zakisan",
    "AusOpen",
    "LetsGameItOut",
    "ykosiris_1",
    "Eret",
    "Macey_Kawns",
    "Vitalikfn_ETH",
    "7ckngMad",
    "singsing",
    "tuonto",
    "omie",
    "fvcksbs",
    "TheViper",
    "Silent",
    "G4TV",
    "Vitalikey_ETH",
    "abce10378",
    "FTLGMarathon",
    "CCT_EN",
    "Blaustoise",
    "Shotz",
    "jisvngl",
    "LexVeldhuis",
    "ams018",
    "FCF",
    "WePlayCSGO",
    "VGBootCamp",
    "me11str0y",
    "GOFNS",
    "ploo",
    "Milk",
    "outt_",
    "catandratshow",
    "Rose_Natts",
    "Doritos",
    "ropz",
    "MyThoughtsOnKP1",
    "PROD",
    "Vitalikwi_Foundation",
    "spoonkid",
    "doughboyspodcast",
    "theneedledrop",
    "DNegsPoker",
    "Gosu",
    "JagmeetSingh",
    "Orjuelac",
    "Mathil1",
    "EXOLsUAE",
    "balenciagajk",
    "OPEX1000",
    "projektmelody",
    "Preachlfw",
    "Marvel",
    "CallMeAgent00",
    "TeamTranstopia",
    "thefoxlive33",
    "smashorange",
    "Priscilla_Kenton",
    "SunlessKhan",
    "Vargskelethor",
    "V4FutureSports",
    "redbyrd",
    "dannyaarons",
    "Scarra",
    "TheStockGuy",
    "Lily_Off_Valley",
    "noelmiller",
    "Cufffem",
    "Snip3down",
    "BarbarousKing",
    "andron1n",
    "WooxSoloqbn",
    "Steelmage",
    "nelkboys",
    "iceiceice",
    "SethEverman",
    "Stoopzz",
    "OpTicGaming",
    "wefoundwossy",
    "franklinweston121",
    "SmiteGame",
    "diorsjinnie",
    "reynad27",
    "sehungago",
    "DansGaming",
    "AxieInfinitydn",
    "GernaderJake",
    "YourPelagea",
    "mitr0",
    "CodeMiko",
    "楓棠1 (mapletom)",
    "Stacey_Lriggs",
    "LevelNextGG",
    "Rebecca_Fmber",
    "EvilGeniuses",
    "FoxholeGame",
    "WooxSolodyo",
    "WooxSolouny",
    "Sommerset",
    "goldbridgetv",
    "lablepret4676737",
    "furiouslyfluffy",
    "FrankDimes",
    "Vitalikiy_ETH",
    "BigDaddy",
    "anders_vejrgang",
    "westonkoury",
    "MLS",
    "TEKKEN",
    "tarzaned",
    "맠동 (jaemahae)",
    "primevideouk",
    "minatoaquach_hololive",
    "Apricot",
    "BoxyFresh",
    "UnrealEngine",
    "Mortdog",
    "Limmy",
    "ToreSays",
    "serahpark_",
    "Paige_Biggs",
    "Vitalikax_Crypto",
    "ETH_Vitalikou",
    "dapr",
    "AdrianaChechik_",
    "ethinvestment",
    "Deadlyslob",
    "MotiveStudio",
    "Vitalikpv_Crypto",
    "TheRunningManZ",
    "EsportsReadyWT",
    "ESL_WC3",
    "oqubuss",
    "thatboydavies19",
    "isthistheendeternnally",
    "physuga",
    "Vitalik_ETH74",
    "vinnie",
    "FIRSTinspires",
    "Lucy_Bilson",
    "WooxSoloryb",
    "th3foxlive",
    "Purpled",
    "Leynainu",
    "drawfeeshow",
    "paradoxkv",
    "robcdee",
    "finalmouse",
    "noctAQ",
    "superjj102",
    "kennyS",
    "Zoomaa",
    "Destiny",
    "skill4ltu",
    "Blooprint",
    "xiath97jk",
    "brandyrenee19",
    "Teo1904",
    "LinusTech",
    "kttyglow",
    "imaqtpie",
    "melina",
    "SquishyMuffinz",
    "catdri",
    "highleauge",
    "KYR_SP33DY",
    "VitalikquCrypto",
    "ConnorEatsPants",
    "Saruei",
    "MenInBlazers",
    "seonghwafiles",
    "EGCTV",
    "TottenhamHotspur",
    "stevewillsendit",
    "Zizaran",
    "Datto",
    "Quinndota",
    "TheRelixChannel",
    "jarnoopmeer",
    "Sequisha",
    "Stacey_Hriggs",
    "sjokz",
    "RedVoxband",
    "Simply",
    "FullSquadGamingTTV",
    "Vitalikrp_Foundation",
    "Millie_Mriggs",
    "investeth",
    "Mia_Pcotts",
    "FaZe",
    "julien",
    "Vitalikmp_Crypto",
    "MartinJensenTV",
    "jibeomiejjang",
    "HarukaKaribu",
    "safyrearch",
    "Vitalikho_Crypto",
    "Saintone",
    "CoconutB",
    "BlackTwitchUK",
    "akaihaato_hololive",
    "빛베리 (berry0314)",
    "martincitopants",
    "Kate_Bawns",
    "Tia_Tcotts",
    "Academy",
    "Sacriel",
    "eLaLiga",
    "stakemladen",
    "Vitalikri_Buterin",
    "Combat",
    "CollegeCarball",
    "loonatheph",
    "SteveSuptic",
    "Zy0xxx",
    "Lucy_Pilliams",
    "hyoon",
    "marialuisadias23",
    "IndieArenaBooth",
    "VitalikbfETH",
    "havocaruvinth",
    "aldogala",
    "sakurizz",
    "Sneegsnag",
    "F1NN5TER",
    "TXShowdownLive",
    "intoheeki",
    "isabeaudelatour",
    "LanuSky",
    "sneakylol",
    "VitalikpiButerin",
    "small_jenny",
    "Burn",
    "CRYPTO_NEWS1",
    "BrawadisReacts",
    "king_live_01",
    "Crunchyroll",
    "buckefps",
    "MrLlamaSC",
    "CDNThe3rd",
    "Euriece",
    "shanks_ttv",
    "MuTeX",
    "Mande",
    "PointCrow",
    "luxuryjjh",
    "juaanm22_",
    "Lucy_Dilliams",
    "JoeWo",
    "Erika_Rones",
    "TLnet",
    "VitalikzlETH",
    "CaptainPuffy",
    "PrimeEdd",
    "AmazonMusicUK",
    "SovietWomble",
    "hannahxxrose",
    "stay_roomnya",
    "PlanetSide2",
    "TheJRM_",
    "Gladd",
    "uccleague2",
    "LearnWithLeon",
    "SelenTatsuki",
    "Splitgate",
    "ForHonorGame",
    "Vitalikhl_Crypto",
    "sashagrey",
    "worldtimeattack",
    "Lucy_Lilson",
    "PRXf0rsakeN",
    "Nightblue3",
    "Glorious_E",
    "VitalikazETH",
    "ItsJSTN",
    "Call of Duty",
    "Vitalikzc_Crypto",
    "4Cast4C",
    "peterpark",
    "UnleashTheFeastTV",
    "Vitaliklc_Crypto",
    "Genburten",
    "Vitalik_EventsDW",
    "kevin11771",
    "Aa9skillz",
    "JokerdTV",
    "Vitaliksf_ETH",
    "Harry",
    "BeyondTheSummit",
    "LEC_Wooloo",
    "GamesRadar",
    "impulseSV",
    "Vitalikdm_Crypto",
    "itsRyanHiga",
    "safyrearchives",
    "EmmaLangevin",
    "3cmgoogie",
    "scoped",
    "VitalikubCrypto",
    "FORMAL",
    "hakumai",
    "arentwealltired",
    "malena",
    "Pyromancer",
    "wanna0n3_mp4",
    "mari_loveskzdream",
    "ElisaEsports",
    "fruitdefense",
    "VitaliktrCrypto",
    "bnans",
    "Vitalikat_Foundation",
    "yoshihoonluvv_",
    "Odablock",
    "Joe_Bartolozzi",
    "HCS",
    "VitalikopCrypto",
    "Chica",
    "JustaMinx",
    "VitaliktaETH",
    "Anton",
    "FACEIT TV",
    "LLStylish",
    "RaccLive",
    "Vitalikty_Crypto",
    "SpectateTyler1",
    "browniesandlemonade",
    "VitalikgkETH",
    "LasVegasVP",
    "scruffoftheneck",
    "Macey_Mawns",
    "TrU3Ta1ent",
    "quake",
    "GeminiTay",
    "Broxah",
    "BigEx",
    "VitalikecCrypto",
    "ESL",
    "krunkerpleague",
    "hexy",
    "GenshinImpactOfficial",
    "dota2ti",
    "Manatreed",
    "daftpunk",
    "Quackity",
    "PGL",
    "Dream",
    "pathofexile",
    "xQc",
    "Asmongold",
    "karljacobs",
    "GeorgeNotFound",
    "tommyinnit",
    "StakeDrake",
    "PGL_Dota2",
    "Corpse_Husband",
    "dota2ti_2",
    "WilburSoot",
    "RanbooLive",
    "RocketLeague",
    "thegameawards",
    "dccomics",
    "AdinRoss",
    "LEC",
    "BLASTPremier",
    "ENST4Y",
    "Riot Games",
    "Sapnap",
    "Bungie",
    "TimTheTatman",
    "LCK",
    "tommyinnitalt",
    "ThisIsNotGeorgeNotFound",
    "Evo",
    "Mizkif",
    "CriticalRole",
    "AustinShow",
    "dreamwastaken",
    "pgl_csgo",
    "HasanAbi",
    "PostMalone",
    "CashApp",
    "playapex",
    "dota2ti_5",
    "Minecraft",
    "Trainwreckstv",
    "VALORANT",
    "LCS",
    "Warframe",
    "Brawlhalla",
    "TenZ",
    "NICKMERCS",
    "ImKaiCenat",
    "Fextralife",
    "ovrtroubledh2o",
    "karlnetwork",
    "Tubbo",
    "loltyler1",
    "yae429",
    "dota2ti_3",
    "do1ezn",
    "WePlayRocketLeague",
    "Schlatt",
    "Rainbow6",
    "s1mple",
    "TurboTax",
    "shroud",
    "WikiDellow",
    "ranboobutnot",
    "RoobetESPORTS",
    "ROSHTEIN",
    "Castro_1021",
    "DreamLeague",
    "TwitchPresents",
    "Sykkuno",
    "OGADotaPIT",
    "Gamers8GG",
    "Arteezy",
    "Xposedmc",
    "Mary_Kown",
    "TSM_ImperialHal",
    "sodapoppin",
    "honaylavender",
    "LIRIK",
    "PrimeVideo",
    "TrashTastePodcast",
    "ludwig",
    "Echo_Esports",
    "IMDb",
    "pokimane",
    "tarik",
    "Xposedyc",
    "OfflineTV",
    "BubiVT",
    "DaequanWoco",
    "DisguisedToast",
    "BruceDropEmOff",
    "dota2ti_4",
    "Nmplol",
    "sfoutsidelands"
]
